getting ready to publish to hashicorp registry
Bonial-International-GmbH/terraform-provider-spinnaker pull request #8
Opened 2021-02-18 16:28 UTC by paulo-sampaio

2021-02-18 19:19 UTC, bonial-botuser commented on .goreleaser
> +      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
I couldn't find this variable in 
https://github.com/crazy-max/ghaction-import-gpg

therefore  I think we should keep in our mind that we must add this in github variables

2021-02-22 09:04 UTC, sidorovdmitry requested changes

2021-02-22 09:04 UTC, sidorovdmitry commented on .github/workflows/release.yml
> +      - 'v*'
I would suggest `v[0-9].[0-9]+.[0-9]+`

2021-02-22 09:04 UTC, sidorovdmitry commented on .goreleaser
> +      - '386'
not sure if we need this

2021-02-22 09:04 UTC, sidorovdmitry commented on .goreleaser
> +      386: i386
not sure if we need this

2021-02-22 09:04 UTC, sidorovdmitry commented on .goreleaser
> +      - '^test:'
please add a new line

2021-02-22 09:11 UTC, martinohmann requested changes

2021-02-22 09:11 UTC, martinohmann commented on .goreleaser
> +---
The file needs to be called `.goreleaser.yml`.

2021-02-22 09:13 UTC, sidorovdmitry commented
We should also change the readme to HCL2 syntax

2021-02-22 15:17 UTC, paulo-sampaio commented
I think i have solved most of the issues, thank you all for the comments.

2021-02-25 14:01 UTC, sidorovdmitry approved these changes

2021-02-26 07:18 UTC, martinohmann approved these changes

2021-03-05 13:39 UTC, merged